### ISSUE TITLE
TransXChange format

### ISSUE THREAD

**Issue by maxwell8888** [hove-io/transit_model#852]
It seems like there was previously support the the TransXChange format but has now been removed. What is the reason it was removed?

**Comment by ArnaudOggy** [comment]
Hello @maxwell8888 ,

We are truly sorry. This is a corporate decision to no longer make this feature available to the public.
This converter is now part of our paid services. 
Feel free to contact [sales@kisio.com](mailto:sales@kisio.com) about this.
