### ISSUE TITLE
Problem with cargo install --path gtfs2netexfr

### ISSUE THREAD

**Issue by GeorgeXen** [hove-io/transit_model#859]
I did clone the URL of the repository to an anaconda shell and then run cargo install --path gtfs2netexfr. Everything looks okay until it reaches 244/249 and it shows Proj-sys(build). I tried it many times and tried to find what is missing but again it doesn't work. Does anyone have the same issue?

![1](https://user-images.githubusercontent.com/69125055/190336772-74efdc61-d09f-4205-9504-422efb158cc1.jpg)

**Comment by pbougue** [comment]
Hi,
Did you have a look at the doc part on PROJ dependency : https://github.com/hove-io/transit_model#proj-dependency ?
This should help (get inspiration/tweak from makefile if it doesn't work right away).

**Comment by pbougue** [comment]
Also, if you don't have PROJ on your system it can be quite long to build, as proj crate downloads and compiles it.

**Comment by ArnaudOggy** [comment]
Hi @GeorgeXen 
Do you necessarily need to compile? 
We never have tested this on Windows
Do you want to modify the Rust code after for your needs?
If not, using docker images might help (https://hub.docker.com/r/navitia/transit_model)
